version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  backend-products:
    build:
      context: ./backend
      dockerfile: Dockerfile-products
    ports:
      - "8080:8080"

  backend-cart:
    build:
      context: ./backend
      dockerfile: Dockerfile-cart
    ports:
      - "8081:8081"

  backend-orders:
    build:
      context: ./backend
      dockerfile: Dockerfile-orders
    ports:
      - "8082:8082"

  backend-notifications:
    build:
      context: ./backend
      dockerfile: Dockerfile-notifications
    ports:
      - "8083:8083"
